//exceptions are expected to pass, because we write the tests to anticipate the errors
exports.Certainfunc=()=>{
    throw new Error('you are entering the wrong data type')
}